// 4. Calculation of π - MPI Bcast and MPI Reduce

#include <stdio.h>
#include <mpi.h>

#define MASTER 0
#define STEPS 100000

int main(int argc, char* argv[])
{
	int rank, n;
    	
	MPI_Init(&argc, &argv);
    	MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    	MPI_Comm_size(MPI_COMM_WORLD, &n);

    	double step = 1.0 / (double) STEPS, share;

    	if (rank == MASTER)
    	{
        	share = STEPS / n;
		printf("Number of processes: %d\n", n);
    	}

	// Broadcast the total steps value to all the processs
    	MPI_Bcast(&share, 1, MPI_DOUBLE, MASTER, MPI_COMM_WORLD);

	// Each process calculates its partial π value
    	double x, sum = 0;
    	for (int i = rank * share; i < (rank + 1) * share; i++)
    	{
        	x = (i + 0.5) * step;
        	sum += 4.0 / (1.0 + x * x);
    	}
    	double pi = step * sum;

	// Reduce the partial π values generated by each process
    	double pisum;
    	MPI_Reduce(&pi, &pisum, 1, MPI_DOUBLE, MPI_SUM, MASTER, MPI_COMM_WORLD);

    	if (rank == MASTER) 
	{
		printf("Calculated value of pi: %lf\n", pisum);
	}

    	MPI_Finalize();
    	return 0;
}
